/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e2e.test.on.docker

import kotlin.test.Test

class MainTest {
    @Test
    fun mainTest() {
        val classUnderTest = Main()
        classUnderTest.test()
    }
}
